- public/.well-known/apple-app-site-association
This restores the state from before the launch of the new homepage last week. 
See: https://web.archive.org/web/20221229230859/https://safe.global/.well-known/apple-app-site-association
And this will hopefully fix: https://github.com/safe-global/safe-ios/issues/2951
> App association file for iOS production app

- src/content/core.json
This updates the "Use our Hackathon Guide" link on the "Core" page to use our new Notion URL.
> fix: migrate Notion link

- src/components/Careers/Intro/styles.module.css
- src/components/Core/Tweets/styles.module.css
- src/components/Wallet/Intro/styles.module.css
Resolves #160 
- Removes the filter on the svg animations
Note: Keeps the filter on the interactive animations as these are disabled automatically on Safari (most likely because the tiles themselves are not part of an svg) but still work in Chrome and Firefox. This could be a possible refactor in the future to have the tile animations as divs.
1. Open the homepage on Safari
2. Navigate to `/core`, `/wallet`, `careers`
3. Observe the tile animations are no longer choppy
> fix: Floating tiles performance

- LICENSE.md
- README.md
- package.json
- Bumps version to 1.0.3
- Adds license info (see https://github.com/safe-global/safe-landing-page/blob/dev/LICENSE.md)
> chore: Bump version to 1.0.3

- src/components/Wallet/NetworkChip/styles.module.css
This adds a border to the "New!" badge according to [the design](https://www.figma.com/file/doceHL65jwlEbAGegLRnq2/Landing-Page?node-id=22-48&t=ZSmtJuZGskLaNgTs-0):
> fix: add border to "New!" badge

- src/components/Careers/Positions/Positions.tsx
- src/hooks/useOpenPositions.ts
Resolves #168
Open positions are now loaded via Ashby.
The badge in the header and chip at the top of the "Careers" page render the count of open positions:
The open positions are listed correctly, linking the Ashby:
> feat: migrate careers to Ashby

- src/components/common/Header/index.tsx
This resolves #180 by removing the open position count from Google via the [`data-nosnippet`](https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag#data-nosnippet-attr) attribute.
> fix: remove position count from search results

- src/components/Ecosystem/Projects/Projects.tsx
This adds a loading indicator for the ecosystem projects, as well as fixing the no results message when only filters are selected.
---
> fix: no results message + loading indicator

- src/components/Ecosystem/Projects/Projects.tsx
This adds the current page number of the Ecosystem page to the search params, also initialising based on the value.
> feat: add pagination to search params

- src/components/Ecosystem/Projects/SidebarAccordion.tsx
- src/content/ecosystem.json
Part of #176 
Adds links according to this [thread](https://5afe.slack.com/archives/C04LENM73JQ/p1683792898777299?thread_ts=1683709710.191559&cid=C04LENM73JQ)
Note that 2 of the links are not configured yet but should be ready next week
1. Open `/ecosystem`
2. Observe all links are set (no more #)
3. Observe the filters are closed by default
> Add links to ecosystem page, close filters by default

- src/content/home.json
This PR replaces the Ecosystem Contact Form link:
- Old one: https://wn2n6ocviur.typeform.com/contactus
- New one: https://ecosystem-contact.safe.global
> fix: Update Ecosystem contact form

- .github/workflows/deploy.yml
We don't have per-branch deployments, so let's at least deploy all branches to dev. If multiple PRs are open at the same time, they will overwrite each other but that's OK.
> Chore: deploy all PR branches to dev

- src/components/Core/Masthead/index.tsx
- src/components/Core/index.tsx
- src/hooks/useDelayedScrollAnimation.ts
Resolves #227 
When opening the Core page, smoothly scrolls to the masthead section.
The target scroll position, ease and duration are reviewed by the design team.
> feat: hook to ease scroll to an element

- src/content/ecosystem.json
- src/content/home.json
- src/content/wallet.json
Resolves Google search results in mobile is displaying the wrong homepage title
1. Reducing the Homepage title length will keep Google from rewriting the page title
2. Adjusted the Wallet and Ecosystem descriptions that are also being rewritten.
> fix: Homepage title

- package.json
- src/components/common/Footer/index.tsx
- src/content/governance.json
> fix: Update gov docs

- src/components/Campaign/Faq/index.tsx
- src/components/Campaign/Hero/index.tsx
- src/components/Campaign/RoundCardGrid/index.tsx
- src/components/Campaign/TextBlockBanner/index.tsx
- src/components/Campaign/TextBlockCentered/index.tsx
- src/components/common/HeaderCTA/index.tsx
- src/contentful/types/TypeFaqEntry.ts
- src/services/analytics/events/socialLogin.ts
- src/services/analytics/trackEvent.ts
Adds tracking to the "Social Login" campaign page according to the shared [doc](https://www.notion.so/safe-global/Tracking-events-Social-login-campaign-page-52c473bee00442e38f82159c1c20a8b9#e5705ffaff5242ae890ffac27a3e5735) 
- Creates an util function to fire a GA4 event
- Uses the tracking function when clicking the elements defined in the documentation
I could only test the events were being received in our analytics dashboard by modifying `useGa.ts` locally. This hook initializes ReactGA4.
> feat: Track "Social Login" campaign

- package.json
- src/components/Campaign/Faq/index.tsx
- src/components/Campaign/Faq/styles.module.css
- src/components/Campaign/Hero/styles.module.css
- src/components/Campaign/RichText/index.tsx
- src/contentful/types/TypeFaqEntry.ts
Small PR to allow FAQ answers to accept markdown.
- Updates `FaqEntry` type
- Opens  RichText Links in a new tab
> feat: turn FAQ answers RichText

- .github/workflows/deploy-release.yml
- .github/workflows/deploy.yml
- src/components/common/MetaTags/index.tsx
Instruct search engine crawlers not to index deployments other that PRODUCTION.
Having `5afe.dev` pages indexed in search engines damages our SEO performance.
> chore: do not index staging and dev deployments

- src/content/core.json
Changes the docs Protocol URL by the 5afe GitHub repo
> chore: change protocol URL

- src/components/Blog/YouTube/index.tsx
- src/lib/__test__/urlPatterns.test.ts
- src/lib/urlPatterns.ts
Enhance the `youtubeRegex` to accept playlists.
Can be tested in https://fix_embeded_entry--homepage.review.5afe.dev/blog/safe-conference-for-web3-berlin-2024
> fix: display Youtube playlists in RichText

- package.json
- src/components/Blog/BannerForm/styles.module.css
- small style fix: the overflow of the background image in `/blog` banner
- `v1.4.5`
> chore: bump package version

- package.json
- src/content/home.json
- src/hooks/useSafeStats.ts
Because Dune's total assets stored query is returning a wrong value we should use the fallback value instead of fetching.
> fix: default to a total assets static value

- src/components/Blog/SearchFilterResults/index.tsx
- src/components/Ecosystem/Projects/Projects.tsx
- src/components/Pressroom/PressReleases/index.tsx
- src/components/Pressroom/index.tsx
- src/components/common/CategoryFilter/index.tsx
- src/components/common/CategoryFilter/styles.module.css
- src/components/common/ShowMoreButton/index.tsx
- src/lib/__test__/getPage.test.ts
- src/lib/containsTag.ts
- src/lib/getPage.ts
- src/pages/press.tsx
Adds the Press releases section on the Pressroom page
Refactors the quick categories filter to its own component in the `/common` folder
https://www.figma.com/file/zNUgOvD1WcFankfXfBiAfs/Press-room?type=design&node-id=9929-4249&mode=design&t=x13Zf5TNtfe0ytJN-0
> Pressroom releases

- package.json
- src/components/Pressroom/index.tsx
Removes a duplicated section in the Pressroom landing page.
> fix: remove duplicated "Press Releases" section

- src/components/Home/HeroVideo/styles.module.css
HeroVideo title styling was broken in desktop Safari due to nested selectors not rendering properly - fixed by removing nesting
> fix: nested h1 span selector was broken in safari

- src/components/Home/SafeAtScale/Ticker.module.css
- src/components/Home/SafeAtScale/TickerElement.tsx
- src/hooks/useScrollReveal.ts
working around a CSS limitation in which `background-clip: text` does not work for relative-positioned children, gradients are now constructed piecewise per-character
> feat: Ticker component text now displays as continuous gradient

- package.json
- src/components/Rewards/SignUpForm/index.tsx
Upon submitting the email, changes button copy to "Submitted!" and disables the button
> feat: add feedback to the SignUp form button

- src/components/Home/SafeAtScale/styles.module.css
- src/components/Token/ButtonsWrapper/index.tsx
- src/components/Token/CenteredTitleCards/styles.module.css
- src/components/Token/LinkCard/styles.module.css
- src/components/common/RichText/index.tsx
- src/components/common/styles.module.css
- give `z-index` to title behind gradient
- accept RichText italic marks
- use 16px `border-radius` in the Token landing page
- use next/link in the SafePass landing page
> styles: homepage styles fix

- src/components/Blog/BlogHome/index.tsx
Do not include Press Release posts in [https://safe.global/blog ](https://safe.global/blog ) to avoid very similar content duplicated.
Example
> feat: do not display "Press Release" posts in the Blog landing page

- .github/workflows/cla.yml
- src/config/routes.ts
- src/pages/cla/index.tsx
Resolves #183
Redirection on the server side was dismissed on https://5afe.slack.com/archives/C049H57FS1E/p1686737485728239?thread_ts=1686069103.973699&cid=C049H57FS1E and preferred to use the correct exact path, ie., without the trailing forward slash.
> fix: remove duplicated page route

- src/components/common/Header/index.tsx
Uses category as map key.
`href` is undefined for the buttons with submenus.
> fix: uses category as map key

- src/components/Pressroom/ContentsNavigation/index.tsx
- src/components/common/LinkCard/styles.module.css
- Open `ContentsNavigation` internal links in the same tab
- Fix Card link text margin
> fix: open internal links in same tab

- src/components/common/Header/index.tsx
The paddings were not applied to the `<span>` element
> fix: links height

- .github/workflows/scheduled-deployment.yml
- Adds a new workflow to run a scheduled build and deployment on the latest tag.
- Given the limitation of Next.js static exports, a new build has to run to include new files in the production server.
> feat: Scheduled deployment CI job

- src/components/DataRoom/VolumeTransferred/index.tsx
- src/components/DataRoom/VolumeTransferred/styles.module.css
- src/content/dataroom.json
Related to #379 
_Note : Please disable TransactionsOnChain component while previewing, as it causes width to increase more than 100vh and displaces all other sections._
> Add mobile support for volume transferred component

- src/components/Blog/ContentsTable/index.tsx
- src/components/Blog/Post/index.tsx
- src/components/Blog/styles.module.css
The social icon in the blog post was incorrectly displaying as green instead of white.
1. Go to one of the blog articles, e.g., [Safe Wallet Introduces Native Swaps](https://style_blog_share_buttons--homepage.review.5afe.dev/blog/safe-wallet-introduces-native-swaps).
2. Verify that the social icon is now white, matching the [designs](https://www.figma.com/design/qtXXlwdslAze6yNbLLzIRa/Website-redesign-2.0?node-id=14969-4870&t=6qwLvCPkIxmVExdW-0).
> fix(blog): sharing icons should inherit the color

- src/components/common/MetaTags/index.tsx
- src/config/securityHeaders.ts
Adds an explicit Content Security Policy to the website pages
Sets the Content Security Policy through a `<meta>` tag
I tried to keep the allowed `src` lists as restrictive as possible without braking anything or lose of functionality
> feat: add CSP header to all the pages

- src/components/DataRoom/VolumeTransferred/SlidingText.tsx
- src/components/DataRoom/WorldGDP/SlidingText.tsx
- src/content/dataroom.json
- src/contexts/SafeDataRoomContext.ts
- src/hooks/useSafeDataRoomStats.ts
- src/pages/dataroom.tsx
- Adapt the World GDP section of the Data room to display the TVP as World GDP percentage.
- Fixes typo `totalVolumeTransfered` -> `totalVolumeTransferred`
> feat: use TVP data instead of TVL for comparison with World GDP

- src/components/Blog/FeaturedPost/index.tsx
- src/components/Blog/FeaturedPost/styles.module.css
- src/components/Governance/Delegates/styles.module.css
Resolves https://github.com/safe-global/safe-homepage/issues/452
- Truncates the _Featured_ post title and excerpt
- CMS: limited the number of chars in a blog post title to 75
Navigate to `/press` or `/blog` and verify the _Featured article_ layout is responsive without breaking the image content
> fix(blog): truncate featured article title and excerpt

- src/components/Wallet/VerticalSlide/Table.tsx
- src/components/Wallet/VerticalSlide/index.tsx
- src/components/Wallet/VerticalSlide/styles.module.css
- src/components/Wallet/VerticalStack/Table.tsx
- src/components/Wallet/VerticalStack/index.tsx
- src/components/Wallet/VerticalStack/styles.module.css
- src/lib/Wallet/selectIndex.ts
Replaces the timer animation for a scroll based animation
> feat: scroll based animation

- src/lib/fetchTotalSafesDeployed.ts
- src/lib/fetchTotalTransactions.ts
The Dune data fetching functions need to return `null` in the catch block, otherwise it cannot be serialized
> fix: return null in the catch block

- src/components/Safenet/CrossChain/index.tsx
Typo regarding cross-chain gas fee.
Changes "gas free" to "gas _fee_".
> fix: cross-chain gas fee typo

- src/components/Agentathon/Partners/index.tsx
Resolves [lint issue](https://github.com/safe-global/safe-homepage/actions/runs/12985474982/job/36210411733)
A `Typography` elemnt was using an invalid `variant` (`body`). This corrects it to using `body1`.
> fix(lint): use correct `variant` of `Typography`

- src/pages/dataroom.tsx
A [build-require](https://github.com/safe-global/safe-homepage/blob/main/src/pages/dataroom.tsx#L10) Dune query 3864414 broke, preventing the build.
This adds default values taken from the currently live homepage as a fallback value.
- Add and return fallback values for data room if query fails.
> fix: add fallback values for data room stats
