- package.json
This updates the version to `1.0.8` in preparation for release of Ashby migration.
> chore: update version to `1.0.8`

- .github/workflows/test.yml
This adds a test workflow to run the tests.
> chore: run tests in ci

- src/config/constants.ts
- src/hooks/useGa.ts
Resolves #200.
These two options are probably redundant but I set both to err on the safe side.
> Fix: set the GA domain

- src/content/ecosystem.json
> Remove fullstop from ecosystem text

- package.json
> chore: Update version to v1.1.1

- src/pages/_document.tsx
Adds structured data to set the website name and alternateName in order to display it in Google Search results as discussed [here](https://5afe.slack.com/archives/C03DAGWJCR5/p1687879426189289)
> Add structured data with website name

- README.md
Document content editing on the website.
> Docs: add info about #admin

- package.json
- src/pages/_document.tsx
> Release 1.2.3

- package.json
- src/content/core.json
- src/content/home.json
- Updates the CTA that links to the whitepaper
- Updates the Safe stats numbers
> feat: update CTA href and Safe stats

- package.json
> chore: Bump version to 1.3.0

- package.json
> chore: bump version to 1.3.1

- src/components/common/ParallaxText/index.tsx
- src/components/common/ParallaxText/styles.module.css
- src/content/governance.json
Updates the `GovernanceProcess` section copy
> feat: update new governance framework content

- package.json
- src/content/careers.json
- Increase package version
- Rewording in the Careers page
> chore: increase package version

- .github/workflows/deploy.yml
Adds a branch named deployment on open PRs
> chore: branch named PR deployment

- src/components/Campaign/TextBlockCentered/styles.module.css
- src/components/Campaign/TitleSpaceBetweenGrid/styles.module.css
- src/components/Campaign/Tweets/styles.module.css
- src/components/Careers/Cards/styles.module.css
- src/components/Core/LinkedCardGrid/styles.module.css
- src/components/Ecosystem/Cards/styles.module.css
- src/components/Ecosystem/Projects/styles.module.css
- src/components/Governance/Delegates/index.tsx
- src/components/Governance/Delegates/styles.module.css
- src/components/Governance/OurMission/styles.module.css
- src/components/Governance/Proposals/styles.module.css
- src/components/Home/BigIconsCardGrid/styles.module.css
- src/components/Home/Stats/styles.module.css
- src/components/Home/TitleTextLinkedCardGrid/styles.module.css
- src/components/Wallet/NetworkChip/index.tsx
- src/components/Wallet/Stepper/index.tsx
- src/components/common/Footer/index.tsx
- src/components/common/HeaderCTA/index.tsx
- src/components/common/LinkButton/styles.module.css
- src/components/common/Networks/index.tsx
- src/styles/globals.css
- Fix some vendor prefix warnings
- Extract transition delay to a global variable
- Adjust Footer as discussed in https://5afe.slack.com/archives/C04LENM73JQ/p1706175487930729
> fix: small css fixes + footer copy update

- .github/workflows/deploy-release.yml
- package.json
Updates the AWS credentials job in the `deploy-release` workflow
> chore: update release workflow

- .github/workflows/deploy-release.yml
- .github/workflows/deploy.yml
- package.json
Apply `permissions: write-all` in both deploy workflows
> chore: stricter workflow permissions

- package.json
- src/components/common/MetaTags/index.tsx
Change web crawlers instruction `none` -> `noindex` as per discussed in th SEO weekly
Thread: https://5afe.slack.com/archives/C06F0BCNMPE/p1707469638358359?thread_ts=1707400469.332749&cid=C06F0BCNMPE
> chore: change web crawlers rule to `noindex`

- package.json
- src/components/Blog/FeaturedPost/styles.module.css
- src/components/Blog/Layout/index.tsx
- src/components/Blog/styles.module.css
Besides bumping the version:
- Minor style fixes
- Change _Sign up_ banner copy
> chore: bump version

- src/content/home.json
Change homepage title as agreed for SEO reasons
> fix: change homepage meta title

- src/components/common/Footer/index.tsx
Resolves https://github.com/safe-global/safe-homepage/issues/260
> Update copyright date

- src/components/Pressroom/Founders/index.tsx
- src/components/Pressroom/LinkCard/styles.module.css
Address some UI feedback given in https://www.notion.so/safe-global/QA-Pressroom-367e07fa2f074795b65204a9ef0b49e8
> Pressroom UI fixes

- src/content/careers.json
- src/content/core.json
- src/content/ecosystem.json
- src/content/governance.json
- src/content/home.json
- src/content/wallet.json
Updates [https://safe.global](url) pages metadata based on the SEO reviewed doc https://www.notion.so/safe-global/Meta-descriptions-safe-global-a6bb06736a6d4c348dcf754a1a4b7e45#c84aea5d08b64cae87a0ee990fad9409
> chore: update pages metadata

- src/components/common/Footer/index.tsx
- src/components/common/Footer/styles.module.css
- src/components/common/Header/styles.module.css
- src/styles/globals.css
Resolves #250 
https://www.figma.com/file/doceHL65jwlEbAGegLRnq2/Landing-Page?type=design&node-id=6456-16069&mode=design&t=irndncgirwHIEdgm-0
> styles: Header blur & mobile height

- src/components/Blog/Layout/index.tsx
- src/components/Campaigns/Campaign/index.tsx
- src/components/Pressroom/index.tsx
- src/components/common/MetaTagsContentful/index.tsx
- src/contentful/types/TypePage.ts
- src/pages/campaigns/[slug].tsx
- move: `Campaigns/MetaTags` -> `common/MetaTagsContentful`
> refactor: move CMS MetaTags to the common folder

- package.json
- src/content/governance.json
Change the Safe Grants Program URL
Request: https://5afe.slack.com/archives/C03CT195S4A/p1713278754363519
> chore: update link to the Safe Grants Program

- src/components/Home/HeroVideo/index.tsx
- src/components/Home/HeroVideo/styles.module.css
- src/components/Home/TextBlockImageManifesto/index.tsx
- src/content/home.json
- video player now waits until data is loaded to fade in, preventing a jump on page load
- replaced hero video with vp9 + hevc versions with alpha channel in order to fix inconsistent bg colours
> fix: Hero video improvements

- src/components/Rewards/IconCarousel/index.tsx
- src/components/Rewards/IconCarousel/styles.module.css
Implements the "Our partners" section
https://www.figma.com/file/qtXXlwdslAze6yNbLLzIRa/Website-redesign-2.0?type=design&node-id=11576-4093&mode=design&t=6FhUVrTNWE5UnyfM-0
> feat: Safe{Pass} carousel

- src/components/Home/Governance/index.tsx
- src/components/Home/Governance/styles.module.css
- src/components/Home/HeroVideo/index.tsx
- src/components/Home/SafeAtScale/index.tsx
- src/components/Home/SafeAtScale/styles.module.css
- src/components/Token/CenteredTextBlockCollapsedMargin/index.tsx
- src/components/Token/ParallaxToken/styles.module.css
- src/components/Token/Tokenomics/index.tsx
- src/components/Token/Tokenomics/styles.module.css
- src/content/home.json
Batch of some style fixes after QA and designers feedback
> styles: fix styles inconsistencies

- src/components/common/Footer/index.tsx
- src/components/common/Footer/styles.module.css
- src/config/routes.ts
Extends the Footer to contain buttons to the Token and Pass pages
https://www.figma.com/file/qtXXlwdslAze6yNbLLzIRa/Website-redesign-2.0?type=design&node-id=12487-144962&mode=design&t=7BAgjn1tDgpw4UuL-0
> feat: update navigation

- src/components/Rewards/SafePass/styles.module.css
> fix: adjust spot position

- src/components/Rewards/SafePass/styles.module.css
- src/components/common/Header/NavigationButton.tsx
- src/components/common/Header/index.tsx
- src/components/common/Header/navCategories.tsx
https://www.figma.com/file/qtXXlwdslAze6yNbLLzIRa/Website-redesign-2.0?type=design&node-id=12520-146768&mode=design&t=SrG7ZuhjV8XVWZQK-0
> feat: add Safe{Pass} button to the navigation

- src/components/common/Header/index.tsx
Fixes key warning `Each child in a list should have a unique "key" prop`
> fix: header key warning

- src/components/Home/SafeAtScale/styles.module.css
- src/content/home.json
- src/content/wallet.json
- correct typo
- replace broken tx-builder URL
> fix: correct typo

- .github/workflows/scheduled-deployment.yml
- package.json
Includes the **Prepare production deployment** script in the `Schedule deployment` workflow
> feat: include "Prepare production deployment script" step

- src/components/Rewards/IconCarousel/index.tsx
- src/components/Rewards/SafePass/index.tsx
- src/components/Rewards/SafePass/styles.module.css
- Displays the partners in the Hero section in a carousel
- Abstracts the `IconCarouselElement` from `IconCarousel` 
Resolves #362
> feat: replace fixed partner logos by the IconsCarousel

- .github/workflows/scheduled-deployment.yml
Update the scheduled build times to run when there is team availability
> chore: update cron times

- src/components/DataRoom/CEXesComparison/index.tsx
- src/components/DataRoom/CryptoPunks/index.tsx
- src/components/DataRoom/Hero/index.tsx
- src/components/DataRoom/IndustryComparison/index.tsx
- src/components/DataRoom/SeeMore/index.tsx
- src/components/DataRoom/TVLComparison/index.tsx
- src/components/DataRoom/TransactionsOnChain/index.tsx
- src/components/DataRoom/USDCStorage/index.tsx
- src/components/DataRoom/VolumeTransferred/index.tsx
- src/components/DataRoom/WorldGDP/index.tsx
- src/components/DataRoom/index.tsx
- src/pages/dataroom.tsx
Bootstrap the page with all sections placeholders
> feat: create dataroom page and sections placeholders

- src/components/DataRoom/LinksWrapper/index.tsx
- src/components/DataRoom/LinksWrapper/styles.module.css
- src/components/DataRoom/WorldGDP/index.tsx
- src/content/dataroom.json
Add buttons component: LinksWrapper
> feat: Links component

- src/components/DataRoom/CryptoPunks/index.tsx
- src/components/DataRoom/CryptoPunks/styles.module.css
- src/components/DataRoom/CryptoPunks/utils.ts
- src/content/dataroom.json
> Add Cryptopunks Component

- public/images/DataRoom/cryptopunk-silhouette.svg
- src/components/DataRoom/CryptoPunks/index.tsx
- src/components/DataRoom/CryptoPunks/styles.module.css
- src/components/DataRoom/CryptoPunks/utils.ts
Imports the SVG rather than creating a component
> fix: import Cryptopunk svg

- src/components/DataRoom/VolumeTransferred/index.tsx
- src/components/DataRoom/VolumeTransferred/styles.module.css
- src/content/dataroom.json
> Add Volume Transferred Component

- src/components/DataRoom/TransactionsOnChain/Counter.tsx
- src/components/DataRoom/TransactionsOnChain/index.tsx
- src/components/DataRoom/TransactionsOnChain/styles.module.css
- src/components/DataRoom/TransactionsOnChain/useCounterScroll.ts
- src/components/DataRoom/TransactionsOnChain/utils.ts
- src/content/dataroom.json
> Add Transactions On Chain Component

- src/components/DataRoom/TransactionsOnChain/Counter.tsx
- src/components/DataRoom/TransactionsOnChain/index.tsx
- src/components/DataRoom/TransactionsOnChain/styles.module.css
- src/components/DataRoom/TransactionsOnChain/useCounterScroll.ts
> Add mobile support for transactions on chain component

- src/components/DataRoom/USDCStorage/MatterCanvas.tsx
- src/components/DataRoom/USDCStorage/MatterJSUtils.ts
- src/components/DataRoom/USDCStorage/index.tsx
- src/components/DataRoom/USDCStorage/styles.module.css
- src/components/DataRoom/USDCStorage/utils/addWallsToWorld.ts
- src/components/DataRoom/USDCStorage/utils/createCoin.ts
- src/components/DataRoom/USDCStorage/utils/types.ts
Relates to #377 
_Note : Please disable TransactionsOnChain component while previewing, as it causes width to increase more than 100vh and displaces all other sections._
> Add mobile layout for USDC storage component

- src/components/GasStation/Hero/styles.module.css
- src/components/GasStation/TextBlockImagePartners/styles.module.css
Button the in Hero section was not clickable
> fix(gas-station): do not give z-index to wrapper container

- src/components/common/Header/index.tsx
- src/components/common/Header/styles.module.css
Add arrow to "Launch Wallet" button as requested per the Legal team
> style: add arrow to Launch Wallet button

- src/components/DataRoom/TransactionsOnChain/styles.module.css
- src/components/DataRoom/USDCStorage/styles.module.css
- src/components/DataRoom/VolumeTransferred/styles.module.css
Addressing QA Comments by @TanyaEfremova on Slack
Related to #376
> QA Improvements

- package.json
- src/content/gas-station.json
- Updates the Gas Station campaign page CTA button
> feat(gas-station): Update CTA button

- src/components/Foundry/Hero/index.tsx
- src/components/Foundry/Hero/styles.module.css
Landing page Hero section
https://www.figma.com/design/kWDCnQXTWb5xZBrNox4ny5/Safe%7BLabs%7D?node-id=1753-638&t=InkODa5bUACEYkJC-0
> feat(foundry): Hero section

- src/components/Foundry/POCs/Card.tsx
- src/components/Foundry/POCs/index.tsx
- src/components/Foundry/POCs/styles.module.css
Implements the POCs table
https://www.figma.com/design/kWDCnQXTWb5xZBrNox4ny5/Safe%7BLabs%7D?node-id=1753-638&t=CHvoCCaF4U5y0od5-0
> feat(foundry): POC table

- package.json
- src/config/securityHeaders.ts
Expands CSP to allow:
- Google Analytics
- ecosystem-database.safe.global
> fix: expand CSP

- src/components/DataRoom/AssetsSecured/SlidingContent.tsx
- src/components/DataRoom/AssetsSecured/styles.module.css
- src/components/DataRoom/CryptoPunks/styles.module.css
- src/components/DataRoom/FeesEarned/styles.module.css
- src/components/DataRoom/Hero/styles.module.css
- src/components/DataRoom/IndustryComparison/styles.module.css
- src/components/DataRoom/SeeMore/styles.module.css
- src/components/DataRoom/TransactionsOnChain/styles.module.css
- src/components/DataRoom/USDCStorage/styles.module.css
- src/components/DataRoom/VolumeTransferred/styles.module.css
- src/components/DataRoom/WorldGDP/styles.module.css
Attempts to modify the scroll experience on mobile browsers to account for them changing the viewport height based on the scroll direction.
> Address Mobile Scroll Issues

- src/components/DataRoom/AssetsSecured/SlidingContent.tsx
- src/components/DataRoom/AssetsSecured/styles.module.css
- src/components/DataRoom/CryptoPunks/styles.module.css
- src/components/DataRoom/FeesEarned/styles.module.css
- src/components/DataRoom/Hero/HeroAnimation.tsx
- src/components/DataRoom/Hero/styles.module.css
- src/components/DataRoom/IndustryComparison/styles.module.css
- src/components/DataRoom/SeeMore/styles.module.css
- src/components/DataRoom/TransactionsOnChain/styles.module.css
- src/components/DataRoom/USDCStorage/styles.module.css
- src/components/DataRoom/VolumeTransferred/styles.module.css
- src/components/DataRoom/WorldGDP/styles.module.css
Fixes the overflow in the Hero Section for mobile screens.
> Mobile Scroll Fix Update

- src/components/DataRoom/CryptoPunks/index.tsx
- src/components/DataRoom/FeesEarned/SlidingContent.tsx
- src/components/DataRoom/FeesEarned/Stack.tsx
- src/components/DataRoom/FeesEarned/index.tsx
- src/components/DataRoom/FeesEarned/styles.module.css
- src/components/DataRoom/Hero/styles.module.css
- src/components/DataRoom/VolumeTransferred/SlidingText.tsx
- src/content/dataroom.json
Addresses copy and UI improvements
> styles(dataroom): UI improvements

- src/components/Safenet/Hero/styles.module.css
- src/components/Safenet/Metatags.tsx
- src/components/common/Header/styles.module.css
- updates the mp4 video asset
- centres the navigation menu badge text
> fix: update video and title

- .github/dependabot.yml
Adds the `dependabot.yml` file to automatically create PRs to update vulnerable dependencies
> chore: add `dependabot.yml`

- .github/workflows/lint.yml
- package.json
- src/contentful/types/TypeAuthor.ts
- src/contentful/types/TypeBaseBlock.ts
- src/contentful/types/TypeBlogHome.ts
- src/contentful/types/TypeButton.ts
- src/contentful/types/TypeExternalUrl.ts
- src/contentful/types/TypeLandingPage.ts
- src/contentful/types/TypeMetaTags.ts
- src/contentful/types/TypePost.ts
- src/contentful/types/TypePressRoom.ts
- src/contentful/types/TypeSimpleBaseBlock.ts
- src/contentful/types/TypeTag.ts
- yarn.lock
Updates Contentful dependency resolving some Dependabot alerts around an old `axios` version.
I had to add a resolution to `package.json` because of this error https://github.com/contentful/contentful.js/issues/2398 on a dependency from the latest `contentful` version.
> chore: update contentful

- package.json
- yarn.lock
Updates Contentful's rich text libraries
> chore: update version contentful rich text dependencies

- src/config/securityHeaders.ts
CSP is blocking embed tweets in the website
> chore: update CSP to allow Twitter embeds

- package.json
Bumps version for release.
Updates version of project to 1.6.5.
> chore: bump version to 1.6.5

- package.json
Bumps version for release.
Updates version of project to 1.6.6.
> chore: bump version to 1.6.6

- package.json
Bumps version for release.
Updates version of project to 1.6.7.
> chore: bump version to 1.6.7

- src/pages/dataroom.tsx
Reverts safe-global/safe-homepage#544
> Revert "fix: add fallback values for data room stats"

- src/components/DataRoom/TransactionsOnChain/CounterContainer.tsx
- src/components/DataRoom/TransactionsOnChain/index.tsx
- src/components/DataRoom/TransactionsOnChain/styles.module.css
Resolves #433
- Attribute responsive `font-size` to the number counter and to the text content
> fix(dataroom): responsive number counter in TransactionsOnChain section

- src/components/Blog/BlogHome/index.tsx
- src/lib/fetchMonthlyActiveUsers.ts
- Provide a category for Safe Research
- Remove Builders Category
> chore:replace Builders category with Safe Research

- README.md
- package.json
- src/contentful/types/TypePost.ts
- src/contentful/types/TypeTag.ts
- Add tag for Safe Research
- Document Type generation in Readme
- Bump version to 1.6.18
> Add tag for Safe Research
